branches:
  only:
    - master

matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      sudo: required
      env: 
        - SWIFT_VERSION="5.1"
    - os: osx
      language: swift
      osx_image: xcode11.1
      env: 
        - CX_COMBINE_IMPLEMENTATION="CombineX"
    - os: osx
      language: swift
      osx_image: xcode11.1
      env: 
        - CX_COMBINE_IMPLEMENTATION="Combine"

env:
  global:
    - PROJECT="CombineX.xcodeproj"
    - SCHEME="CombineX-Package"
    - DESTINATION="platform=iOS Simulator,OS=13.1,name=iPhone 8"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)";
    fi

# Travis does not yet support macOS 10.15, so we have to generate an iOS project to test against `Combine`.
script:
  - if [[ $CX_COMBINE_IMPLEMENTATION == 'Combine' ]]; then
      gem install xcpretty;
      swift package generate-xcodeproj;
      xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty;
    else
      swift test -Xswiftc -suppress-warnings;
    fi