env:
  global: 
    - WORKSPACE="Specs.xcworkspace"
    - SDK="iphonesimulator13.0"
    - DESTINATION="platform=iOS Simulator,name=iPhone X,OS=13.0"

matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.0"
      sudo: required
    - os: osx
      language: swift
      osx_image: xcode11.0
      env:
        - SCHEME="CombineX"
    - os: osx
      language: swift
      osx_image: xcode11.0
      env:
        - SCHEME="Specs"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      gem install xcpretty;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)";
    fi

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      cd Specs;
      echo "Start testing $SCHEME...";
      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      swift test;
    fi
