language: generic
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      env: SWIFT_VERSION="5.0"
    # - os: osx
    #   osx_image: xcode11.0

# cache: bundler

before_install:
  # - gem update --system
  # - gem install bundler
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    fi

script:
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
  #     bundle exec fastlane test;
  #   fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      swift test;
    fi
