matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.1"
      sudo: required
    - os: osx
      language: swift
      osx_image: xcode11.1
    - os: osx
      language: swift
      osx_image: xcode11.1
      env: USE_COMBINE="YES"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)";
    fi


# swift test -Xswiftc -DUSE_COMBINE;

script:
  - if [[ $USE_COMBINE == 'YES' ]]; then
      ./ci/test-combine;
    else
      swift test;
    fi