env:
  global: 
    - WORKSPACE="Specs.xcworkspace"

matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.1-DEVELOPMENT-SNAPSHOT-2019-09-05-a"
      sudo: required
    - os: linux
      language: generic
      dist: xenial
      env: SWIFT_VERSION="5.0"
      sudo: required
    - os: osx
      language: swift
      osx_image: xcode10.3
    - os: osx
      language: swift
      osx_image: xcode11
    - os: osx
      language: swift
      osx_image: xcode11
      env: USE_COMBINE="YES"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)";
    fi

script:
  - if [[ $USE_COMBINE == 'YES' ]]; then
      swift test -Xswiftc -DUSE_COMBINE;
    else
      swift test;
    fi